### ISSUE TITLE
assoc0file Pv matrix

### ISSUE THREAD

**Issue by nhorwitz** [PMBio/GNetLMM#6]
Hi,

When I run the initial association scan, with the command: 
"for i in $(seq 0 10000 40000)
do
    ./gNetLMM_analyse --initial_scan --bfile plink1 --pfile GE_noNA_NM_biom_ord --cfile "mod.cov" --assoc0file assoc0file --startSnpIdx $i --nSnps 10000 --ffile "covariates_no_names_sex_condition_n.txt" 
done
I end up with all my pv.matrix files having nothing but 'nan.' I did some searching and it looks like the G.T matrix generated in gnetlmm.py also contains some 'nan's. Any clue what could be the issue. Im guessing its an issue with one of my files but I cant seem to figure out which one. 

On the other hand, If I dont specify nSnps or startSnpIdx, I end up with the following error:
"Traceback (most recent call last):
  File "./gNetLMM_analyse", line 53, in <module>
    analyse(options)
  File "/n/regal/wagers_lab/nhorwitz/GNetLMM/GNetLMM/pycore/utils/analyseCore.py", line 279, in analyse
    memory_efficient=options.memory_efficient)
  File "/n/regal/wagers_lab/nhorwitz/GNetLMM/GNetLMM/pycore/utils/analyseCore.py", line 208, in initial_scan
    beta0, pv0 = model.initial_scan(startSnpIdx, nSnps,memory_efficient)
  File "/n/regal/wagers_lab/nhorwitz/GNetLMM/GNetLMM/pycore/modules/gnetlmm.py", line 128, in initial_scan
    lm = qtl.qtl_test_lmm(snps=G.T, pheno=Y.T, K=self.K, covs=self.Covs)
  File "/n/home10/nhorwitz/.conda/envs/ody/lib/python2.7/site-packages/limix_legacy/modules/qtl.py", line 212, in qtl_test_lmm
    lmm_ = lmm(snps=snps, pheno=pheno, K=K, covs=covs, test=test, NumIntervalsDelta0=NumIntervalsDelta0, NumIntervalsDeltaAlt=NumIntervalsDeltaAlt, searchDelta=searchDelta, verbose=verbose)
  File "/n/home10/nhorwitz/.conda/envs/ody/lib/python2.7/site-packages/limix_legacy/modules/qtl.py", line 76, in __init__
    self.process()
  File "/n/home10/nhorwitz/.conda/envs/ody/lib/python2.7/site-packages/limix_legacy/modules/qtl.py", line 102, in process
    self._lmm.process()
  File "/n/home10/nhorwitz/.conda/envs/ody/lib/python2.7/site-packages/limix_legacy/deprecated/core.py", line 11547, in process
    return _core.CLMM_process(self)
RuntimeError: Unknown exception"

This error is completely throwing me off. Any guesses what could be wrong?

Thanks!

**Comment by brakitsch** [comment]
Hi,

the G-matrix contains the genotypes - does the bed-file contain missing 
values? unfortunately the methods cannot deal with them. My guess is 
that you can circumvent the problem if you impute them.


Best,
BArbara


------ Originalnachricht ------
Von: "nhorwitz" <notifications@github.com>
An: "PMBio/GNetLMM" <GNetLMM@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Gesendet: 23.11.2017 15:49:54
Betreff: [PMBio/GNetLMM] assoc0file Pv matrix (#6)
